language: node_js

node_js:
  - "6"

before_install:
  - pip install --user codecov
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - codecov --file coverage/coverage.json --disable search